# Generated by Django 3.1.4 on 2021-01-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Markname', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='models/')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('time', models.IntegerField()),
                ('deskription', models.TextField()),
                ('img', models.ImageField(upload_to='marks/')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mark')),
            ],
        ),
    ]
