# Generated by Django 3.1.4 on 2021-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210114_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='volume',
            field=models.FloatField(),
        ),
    ]
